# Generated by Django 2.2 on 2019-05-12 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaintStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='userID',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='subSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
            ],
        ),
        migrations.CreateModel(
            name='machineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('NoOfMachine', models.IntegerField()),
                ('sections', models.ManyToManyField(to='api.section')),
                ('subsections', models.ManyToManyField(to='api.subSection')),
            ],
        ),
        migrations.CreateModel(
            name='machineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='machineType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machineType'),
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(max_length=5)),
                ('problem', models.TextField()),
                ('breakDownTime', models.TimeField(auto_now_add=True)),
                ('Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('jobType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobType')),
                ('machineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('machineType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.machineType')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaintStatus')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subSection')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(max_length=5)),
                ('actionTaken', models.TextField()),
                ('remarks', models.TextField()),
                ('startTime', models.TimeField()),
                ('handoverTime', models.TimeField()),
                ('Attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
                ('RefNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaint')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.complaintStatus')),
            ],
        ),
    ]
