# Generated by Django 2.2 on 2019-05-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190512_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='machineType',
            new_name='machinetype',
        ),
    ]
